### ISSUE TITLE
user profile pages not styled

### ISSUE THREAD

**Issue by kinghat** [Mottie/Darker-Medium#10]
* **Browser**: chrome 70 stable
* **Operating System**: linux
* **URL of the problem page**: user profile pages

![image](https://user-images.githubusercontent.com/16073360/48435068-1ff76e80-e741-11e8-8ab2-ddcfdbf7373d.png)

**Comment by Mottie** [comment]
Hi @k1nghat!

The problem is that Medium doesn't use the same templates for the profile pages. It's very difficult to style these pages since all the class names are one or two letters long

![](https://user-images.githubusercontent.com/136959/48440648-170d9980-e74f-11e8-88f8-8ca211f3a678.png)

I may be able to add some generic CSS to style the page, but it would only work with the UserCSS and not the browser extension. The reason is the browser extension looks for specific attributes in the `<head>` which aren't included with the profile pages.

Please try out this UserCSS and let me know if it looks okay... I'll include it in the next release.

-----

_Edit_: Moved css into a file in this repo.

Install profile & topics usercss using this button: 

[![Install the extras usercss](https://img.shields.io/badge/Install%20extras%20usercss%20with-Stylus-285959.svg)](https://raw.githubusercontent.com/Mottie/Darker-Medium/master/darker-medium-extras.user.css)

**Comment by kinghat** [comment]
looks good. tyvm!
![image](https://user-images.githubusercontent.com/16073360/48441704-d7947c80-e751-11e8-873c-0a6dc53fcb03.png)
though there is this:
![image](https://user-images.githubusercontent.com/16073360/48441801-0a3e7500-e752-11e8-8ab3-e78c6365e9b2.png)
and this under: https://medium.com/me/stories/drafts
![image](https://user-images.githubusercontent.com/16073360/48441826-1de9db80-e752-11e8-88ce-7012c2b96a74.png)

**Comment by Mottie** [comment]
Update: Moved CSS snippet above into a file in the repo.

Install profile & topics usercss using this button: 

[![Install the extras usercss](https://img.shields.io/badge/Install%20extras%20usercss%20with-Stylus-285959.svg)](https://raw.githubusercontent.com/Mottie/Darker-Medium/master/darker-medium-extras.user.css)
