### ISSUE TITLE
Stylus Extension & Security Concerns

### ISSUE THREAD

**Issue by nikolay** [Mottie/Darker-Medium#2]
For those who are concerned about security, you should offer a Stylus extension as well.

**Comment by Mottie** [comment]
Hi @nikolay!

There should be no security concerns with this extension &mdash; I'll add a section to the readme repeating what I state here. Anyone can examine the code for the extension to verify this statement:

This browser extension **does not collect any personal data**. The only data stored is the user style preferences (the state of the extension, five colors &amp; an underline setting). Absolutely nothing else is shared or tracked; it's not using Google Analytics.

As for a Stylus userstyle, I could create one, but it would have to be manually updated to include every Medium story domain; there are so many and I don't have the time to always keep the list up-to-date... I did bring up a suggestion with the other developers of Stylus in [this issue](https://github.com/openstyles/stylus/issues/136) to allow targeting a selector within the HTML; but it was rejected, and my suggestion to [wicg](https://discourse.wicg.io/t/status-of-document-rule-proposal/2222) to extend the `@-document` rule didn't appear to gather much interest. That is how this extension was born.

Since it's probably not a bad idea, I think I'll go ahead and create a userstyle that can be used by Stylus; but, I think I'll make it as a usercss style &mdash; allowing it to be installed directly from GitHub. This will soon be supported by Stylus (see [PR #134](https://github.com/openstyles/stylus/pull/134)). I'll also host it on freestyler.ws. I'm still undecided about userstyles.org... the new owners are seriously neglecting their site and extension.

**Comment by Mottie** [comment]
[![Install the usercss](https://img.shields.io/badge/Install%20directly%20with-Stylus-285959.svg)](https://raw.githubusercontent.com/Mottie/Darker-Medium/master/darker-medium.user.css)
