### ISSUE TITLE
Error on text color

### ISSUE THREAD

**Issue by lucazambon** [Mottie/Darker-Medium#6]
* **Google Chrome v.65.0.3325.181**:
* **Mac OS High Sierra v.10.13.4**:
* **https://medium.com/me/email-settings/**:

Hi,
I've found another little error on label text-color on the email-settings pages:

![schermata 2018-04-09 alle 11 40 47](https://user-images.githubusercontent.com/35226809/38491043-18261f46-3beb-11e8-94c0-f276ed6c14b8.png)

I think the green button should have a **white text-color**

**Comment by Mottie** [comment]
Hi @lucazambon!

I've updated the style, but I haven't released it yet; maybe later tonight or tomorrow when I get more time.

I didn't set the text color to white since the contrast wasn't good, so I changed it to match the main accent colors

![](https://user-images.githubusercontent.com/136959/38515273-5d95c118-3bf9-11e8-8d75-5425a53fc80a.png)

**Comment by lucazambon** [comment]
Hi @mottie,
Okok, mine was just a suggest. It’s pretty like this too. 
Nice job dude.
