### ISSUE TITLE
Following button background color extends its button container

### ISSUE THREAD

**Issue by laurensiusadi** [Mottie/Darker-Medium#7]
* **Browser**: Firefox 62.0.3
* **Operating System**: Windows 10 64bit
* **URL of the problem page**: https://medium.freecodecamp.org/how-to-become-more-productive-while-working-less-9b9be71e9141

'Following' button background color extends its button container. Not sure if it was padding or something.

![firefox_2018-10-07_11-36-07](https://user-images.githubusercontent.com/5661040/46578258-4c72e900-ca25-11e8-9f2d-9eec4296e014.png)

**Comment by Mottie** [comment]
Hi @laurensiusadi!

Thanks for letting me know! I have this fixed in the master branch of this repository, but I'm holding off on updating the extension until I figure out what to do about the profile pages (e.g. https://medium.com/@wowmotty). The extension doesn't detect those pages as a medium page and looks really ugly when partially styled with the UserCSS. The Medium folks styled the page with one & two letter class names, so it's really difficult to deal with it :(
